trigger: none  # Change this trigger as needed

pool:
  # Define your agent pool

variables:
  # Define any variables needed for the PR creation

steps:
- task: createpullrequest@1  # Replace 1 with the extension version
  inputs:
    connection: test-oraganization  # Replace with your GitHub connection name
    title: ${{ var.prTitle }}  # PR title (can be dynamic using variables)
    description: "hello this the new pR" # PR description (can be dynamic)
    targetBranch: main  # Target branch for the PR
    sourceBranch: feature/testing  # Source branch for the PR