trigger: none  # Change this trigger as needed

pool:
  # Define your agent pool

variables:
  # Define any variables needed for the PR creationndkdk dkdk

steps:
- task: shayki.createpullrequest@1  # Replace 1 with the extension version
  inputs:
    connection: your-github-connection  # Replace with your GitHub connection name
    title: ${{ var.prTitle }}  # PR title (can be dynamic using variables)
    description: ${{ var.prDescription }}  # PR description (can be dynamic)
    targetBranch: main  # Target branch for the PR
    sourceBranch: feature/my-branch  # Source branch for the PR
     reviewers: reviewer1, reviewer2  # Comma-separated list of reviewers (optional)
